services:
  postgres:
    image: postgres:15-alpine
    container_name: spice_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spice_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: spice_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      target: release
    env_file:
      - .env
    environment:
      PORT: "8080"
      DB_DSN: "host=postgres user=postgres password=postgres dbname=spice_db port=5432 sslmode=disable"
      REDIS_ADDR: "redis:6379"
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

  api_debug:
    build:
      context: .
      target: debug
    env_file:
      - .env
    environment:
      PORT: "8080"
      DB_DSN: "host=postgres user=postgres password=postgres dbname=spice_db port=5432 sslmode=disable"
      REDIS_ADDR: "redis:6379"
    depends_on:
      - postgres
      - redis
    ports:
      - "8081:8080"
      - "2345:2345"

  migrate:
    build:
      context: .
      target: release
    env_file:
      - .env
    environment:
      DB_DSN: "host=postgres user=postgres password=postgres dbname=spice_db port=5432 sslmode=disable"
      REDIS_ADDR: "redis:6379"
    depends_on:
      - postgres
      - redis
    entrypoint: ["/app/migrate"]
    command: ["up"]

volumes:
  postgres_data:
  redis_data:
